fieldLayouts:
  879ce0e0-1191-4099-bd57-1615902130c0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bb62ec74-9871-4b78-99b1-6a3a04dd80ec
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 90d8146e-d7f8-4903-a659-d887f933009d # Rich Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7fc879bb-e0de-4022-8f3a-6533df7da13b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0f7b0506-55c7-4782-be1f-ba1869ae6479
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: f121205f-fde4-4b92-be59-8f673b575f7f # General Pages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
