fieldLayouts:
  3bb3884d-ad6c-4c3c-bd32-6e3f68dbcb47:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4c282d8a-d9a3-484c-8bd7-905d58d564e3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d71c5524-c34b-4b5a-97a0-86d1acb8ad2a # Photos
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ca955ea-fbb8-468a-b1a2-e434f17a0bbe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 484750fa-dca6-4872-a932-c9598c45a972 # Short Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 765e1e51-9178-4563-9e28-a90994781462
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 90d8146e-d7f8-4903-a659-d887f933009d # Rich Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0032ca9c-2fcd-4ce9-92b9-ef74dab0cb8d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0fca5cfe-887f-47a6-8265-95975475b4e8
        userCondition: null
handle: stories
hasTitleField: true
name: Stories
section: a1c5cbfa-a919-4a86-8fbd-4d8f3bb23074 # Stories
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
