fieldLayouts:
  3fca066d-9e52-4a56-aa47-31efdcb0805f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 0de5840e-8e11-437c-9a03-8b6454e5910b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e46150f9-b6ea-4bc9-aed8-984cbcf58f63
        userCondition: null
fs: uploads
handle: uploads
name: Uploads
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: uploads
transformSubpath: ''
