columnSuffix: null
contentColumnType: string
fieldGroup: fc7d2509-e3ec-48c0-b2be-b5d34765c806 # Homepage
handle: featuredStory
instructions: null
name: 'Featured Story'
searchable: false
settings:
  allowSelfRelations: false
  localizeRelations: false
  maxRelations: 1
  minRelations: 1
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: 'Select a featured story'
  showSiteMenu: false
  source: null
  sources:
    - 'section:a1c5cbfa-a919-4a86-8fbd-4d8f3bb23074' # Stories
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
