columnSuffix: null
contentColumnType: string
fieldGroup: bd7156df-5b07-4b76-870f-150e04a37f45 # Common
handle: navLinks
instructions: null
name: 'Nav Links'
searchable: false
settings:
  contentTable: '{{%matrixcontent_navlinks}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
