columnSuffix: mloxvtan
contentColumnType: text
fieldGroup: bd7156df-5b07-4b76-870f-150e04a37f45 # Common
handle: shortDescription
instructions: null
name: 'Short Description'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
