defaultPlacement: end
enableVersioning: true
handle: generalPages
name: 'General Pages'
propagationMethod: all
siteSettings:
  c79d4167-a621-4039-b972-318e8534bbf1: # My Test Craft Site
    enabledByDefault: true
    hasUrls: true
    template: general.twig
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: 2
  uid: dd028959-417e-454d-adcb-9ab310c1f6e1
type: structure
