defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  c79d4167-a621-4039-b972-318e8534bbf1: # My Test Craft Site
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
