defaultPlacement: end
enableVersioning: true
handle: stories
name: Stories
propagationMethod: all
siteSettings:
  c79d4167-a621-4039-b972-318e8534bbf1: # My Test Craft Site
    enabledByDefault: true
    hasUrls: true
    template: stories/_entry
    uriFormat: 'stories/{slug}'
type: channel
